# Site wide configuration

title:            Past Ecstasies
locale:           en_US
url:             //dgupta.us 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Dhananjay Gupta
  avatar: bio-photo-DJ.jpg
  bio: "Seeker! eager to know the ultimate."
  email: dgupta25@uic.edu
  disqus-shortname:
  twitter: dhananj00137780
  facebook: dhananjay.gupta.79219
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: DhananjayGupta300 
  stackoverflow: https://stackoverflow.com/users/9270496/dhananjay-gupta
  linkedin: dhananjaygupta30
  xing: #username
  instagram: dgupta30
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
